import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'DebtDispute terms of service.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-navy-950 py-16">
      <div className="max-w-3xl mx-auto px-4 sm:px-6">
        <h1 className="text-3xl font-bold text-white mb-8">Terms of Service</h1>
        <div className="text-slate-300 text-sm leading-relaxed space-y-5">
          <p><strong className="text-white">Last Updated:</strong> March 2025</p>
          <h2 className="text-white text-xl font-bold mt-6">Not Legal Advice</h2>
          <p>
            DebtDispute provides document preparation assistance only. We are not a law firm and
            we do not provide legal advice. The letters generated by this service are templates
            based on general consumer protection law and do not constitute legal advice specific
            to your situation. Always consult a licensed attorney for legal counsel.
          </p>
          <h2 className="text-white text-xl font-bold mt-6">Use of Service</h2>
          <p>
            You may use DebtDispute only for lawful purposes and in connection with legitimate
            consumer debt disputes. You may not use our service to harass, defraud, or make false
            claims against any party.
          </p>
          <h2 className="text-white text-xl font-bold mt-6">Accuracy of Information</h2>
          <p>
            While we strive to provide accurate statute of limitations data and legal citations,
            laws change and individual circumstances vary. We make no warranty as to the accuracy
            or completeness of the information provided. Verify all legal information with an
            attorney before acting on it.
          </p>
          <h2 className="text-white text-xl font-bold mt-6">Payments and Refunds</h2>
          <p>
            One-time purchases are non-refundable after PDF download. Subscriptions may be
            cancelled at any time; cancellation takes effect at the end of the current billing
            period. Contact us within 7 days of purchase for refund inquiries.
          </p>
          <h2 className="text-white text-xl font-bold mt-6">Limitation of Liability</h2>
          <p>
            DebtDispute is not liable for any outcomes resulting from the use of letters
            generated by this service. Results depend on many factors beyond our control,
            including the specific facts of your situation and the actions of the debt collector.
          </p>
        </div>
      </div>
    </div>
  );
}
